import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className }>
        <div className="max-w-[1600px] m-auto">
        
        <nav className="bg-gray-300">
          <div className="py-2 px-40 flex justify-between items-center">
            <span className="text-3xl font-bold py-2 px-4 rounded-lg bg-blue-600 cursor-pointer hover:bg-blue-800">
              C

            </span>
            <ul className="flex gap-4 ">
              <li>
                <a className="py-2 px-4 hover:bg-black hover:text-white rounded-lg" href="/">
                  Home
                </a>
              </li>
              <li>
                <a className="py-2 px-4 hover:bg-black hover:text-white rounded-lg" href="/about">
                  About
                </a>
              </li>
              <li>
                <a className="py-2 px-4 hover:bg-black hover:text-white rounded-lg" href="/product">
                  Product
                </a>
              </li>
              
            </ul>
            <div className="flex gap-4 items-center">
                <svg
                  stroke="currentColor"
                  fill="currentColor"
                  stroke-width="0"
                  viewBox="0 0 16 16"
                  class="cursor-pointer"
                  height="1em"
                  width="1em"
                  xmlns="http://www.w3.org/2000/svg"
                >
                 
                </svg>
              <div class="indicator">
             
              </div>
            </div>
          </div>
        </nav>
        {children}
        </div>
      </body>
    </html>
  );
}
